CREATE TABLE "entidades" (
  "id_entidad" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "codigo" text NOT NULL,
  "nombre" text NOT NULL
);

CREATE TABLE "trimestres" (
  "id_trimestre" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nombre" TEXT NOT NULL UNIQUE
);

CREATE TABLE "periodos" (
  "id_periodo" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_trimestre" BIGINT NOT NULL,
  "año" INTEGER NOT NULL,
  FOREIGN KEY ("id_trimestre") REFERENCES "trimestres" ("id_trimestre")
);

CREATE TABLE "descripcion" (
  "id_descripcion" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "codigo" text NOT NULL,
  "descripcion" text NOT NULL
);

CREATE TABLE "estados" (
 "id_estado" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nombre" TEXT not null
);

CREATE TABLE "registros_scraping" (
    "id_registro" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "id_entidad" BIGINT NOT NULL,
    "id_periodo" BIGINT NOT NULL,
    "fecha_scraping" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "estado" estados,
    FOREIGN KEY ("id_entidad") REFERENCES "entidades" ("id_entidad"),
    FOREIGN KEY ("id_periodo") REFERENCES "periodos" ("id_periodo")
);

CREATE TABLE "fac_tesoreria_fondo_salud" (
  "id_tesoreria_fondo_salud" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_entidad" bigint NOT NULL,
  "id_descripcion" bigint NOT NULL,
  "id_periodo" bigint NOT NULL,
  "regimen_subsidiado_pesos" float NOT NULL,
  "salud_publica_colectiva_pesos" float NOT NULL,
  "prestacion_del_servicio_oferta_pesos" float NOT NULL,
  "otros_gastos_salud_inversion" float NOT NULL,
  "otros_gastos_salud_funcionamiento" float NOT NULL,
  "saldo_otras_cuentas_transferencias_pendientes" float NOT NULL,
  "total_cuentas_maestras" float NOT NULL
);

ALTER TABLE "registros_scraping" ADD FOREIGN KEY ("id_estado") REFERENCES "estados" ("id_estado");

ALTER TABLE "fac_tesoreria_fondo_salud" ADD FOREIGN KEY ("id_entidad") REFERENCES "entidades" ("id_entidad");

ALTER TABLE "fac_tesoreria_fondo_salud" ADD FOREIGN KEY ("id_periodo") REFERENCES "periodos" ("id_periodo");

ALTER TABLE "fac_tesoreria_fondo_salud" ADD FOREIGN KEY ("id_descripcion") REFERENCES "descripcion" ("id_descripcion");
